name: Validate Home Assistant Integration

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: hassfest-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hassfest:
    name: hassfest
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Run hassfest
        uses: "home-assistant/actions/hassfest@master"
